title: Content Creation
description: A simple blog for CSCI 340
baseurl: "/csci340blog"
url: "awriterish.github.io"
paginate: 5

social:
  github: awriterish
  twitter: awriterish
  email: awriterish@outlook.com

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
